name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        java: [8]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
      - run: sbt clean coverage test coverageReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true